### ISSUE TITLE
Discount codes

### ISSUE THREAD

**Issue by samikeijonen** [samikeijonen/edd-members#10]
Here the idea from Twitter: if a users membership duration == 1 month -> 2% discount, if 2 months -> 4%, to build incentive to stay as a member :)

I was thinking could it be more useful to set discount codes for variable prices? Because when you enable variable pricing you can set different membership length for different prices. In the same time you could set discount %.

**Comment by samikeijonen** [comment]
Discount Pro might do the job: 

https://easydigitaldownloads.com/extensions/discounts-pro/

**Comment by tnorthcutt** [comment]
+1 for using Discounts Pro to handle this if it can. That kind of discount setup feels overly complicated for what should be (IMO) a very focused and lean membership extension.

**Comment by samikeijonen** [comment]
Agreed, this is not a goal for this plugin.
