### ISSUE TITLE
WP_DEBUG user expire date notices/warnings

### ISSUE THREAD

**Issue by justintadlock** [samikeijonen/edd-members#11]
When a user doesn't have an expire date, there's some `WP_DEBUG` notices and warnings output in the edit user expire date form field.  These are output in the `value` attributes of the `<inputs>`

**Date:**

	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>112</b><br />
	<br />
	<b>Notice</b>:  Undefined index: 00 in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>271</b><br />
	<br />
	<b>Notice</b>:  Undefined index:  in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>287</b><br />
	<br />
	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>114</b><br />
	<br />
	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>116</b><br />
	<br />
	<b>Notice</b>:  Undefined offset: 0 in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>302</b><br />
	<br />
	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>117</b><br />
	<br />
	<b>Notice</b>:  Undefined offset: 0 in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>302</b><br />

**Hour:**

	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>112</b><br />
	<br />
	<b>Notice</b>:  Undefined index: 00 in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>271</b><br />
	<br />
	<b>Notice</b>:  Undefined index:  in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>287</b><br />
	<br />
	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>114</b><br />
	<br />
	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>116</b><br />
	<br />
	<b>Notice</b>:  Undefined offset: 0 in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>302</b><br />
	<br />
	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-includes\functions.php</b> on line <b>117</b><br />
	<br />
	<b>Notice</b>:  Undefined offset: 0 in <b>C:\xampp\htdocs\wp-includes\locale.php</b> on line <b>302</b><br />

**Minute:**

	<b>Warning</b>:  date() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\wp-content\plugins\edd-members\includes\user-meta.php</b> on line <b>127</b><br />

**Comment by samikeijonen** [comment]
Thanks! I look into it.

**Comment by samikeijonen** [comment]
Commit 8ce3e097b1f3109f273475924ae0b1498c565187 should fix this.
