### ISSUE TITLE
Name shortcode

### ISSUE THREAD

**Issue by samikeijonen** [samikeijonen/edd-members#12]
Here is request from the user. Should we add shortcode for name that we could use in the front end?

```Hi [edd_members_name], your memberships expires at [edd_members_expire_date].```

I could add that kind of shortcode. But then again there are lot’s of plugins that already do that, like [this one](https://wordpress.org/plugins/user-shortcodes/).

**Comment by samikeijonen** [comment]
@justintadlock @tnorthcutt Do you happen to have opinion on this one?

**Comment by tnorthcutt** [comment]
@samikeijonen I think I'd vote for adding it, rather than suggesting the installation of another plugin. It definitely makes sense and is probably a very common use-case, and it's also a "feature" that wouldn't get in the way or cause clutter for people who don't want or need to use it.

**Comment by justintadlock** [comment]
I think it'd be a good idea.  Actually, I've got a use case I'm working on where I could actually use that myself.  I was just going to do it via PHP (might still, depending on how I build it), but a shortcode would come in handy.

**Comment by samikeijonen** [comment]
Thanks for feedback. I was thinking doing something like this:

```
function edd_members_name_shortcode( $atts, $content = null ) {
	
	$atts = shortcode_atts( array(
		'field'   => 'display_name',
	), $atts );
	
	// Bail if user is not logged in
	if ( ! is_user_logged_in() ) {
		return;
	}
	
	// Return current user name or any other author meta when using field attribute
	return get_the_author_meta( esc_attr( $atts['field'] ), get_current_user_id() );
	
}
add_shortcode( 'edd_members_name', 'edd_members_name_shortcode' );
```

**Comment by samikeijonen** [comment]
This is added in commit 69b9d162693edd7b6d3c5f9dcfce4c85ca68afdf.
