### ISSUE TITLE
Errors when bbPress isn't activated

### ISSUE THREAD

**Issue by bekarice** [samikeijonen/edd-members#13]
Looks like [`$edd_members_is_bbpress`](https://github.com/samikeijonen/edd-members/blob/master/templates/content-private.php#L37) isn't defined unless `is_bbpress()` exists, which throws this error on restricted content without bbPress:

```
Notice: Undefined variable: edd_members_is_bbpress in /wp-content/plugins/edd-members/templates/content-private.php on line 37
```

Should probably define as `false` first before L32, then let bbPress change it if active :smile_cat:

**Comment by samikeijonen** [comment]
Thanks, I look into it.

**Comment by samikeijonen** [comment]
Thanks for tip. This will be in next update.

```
		// Do not show login form in bbPress content
		$edd_members_is_bbpress = false;
		if( function_exists( 'is_bbpress' ) ) :
			$edd_members_is_bbpress = is_bbpress();
		endif;
```

**Comment by samikeijonen** [comment]
This is added in commit e1952ef6d4b7ccd492cf8a49e7363d2b5835ed20.
