### ISSUE TITLE
Differences with content restriction?

### ISSUE THREAD

**Issue by planetahuevo** [samikeijonen/edd-members#16]
I am trying to find the diferences between this and the Content Restriction addon. 
https://easydigitaldownloads.com/downloads/content-restriction/

After some search and reading I am not sure. 
Can anyone higlight the main differences or why to use one or the other?

Thanks!

**Comment by samikeijonen** [comment]
I'd probably just try them out. Here is [info about this one](https://foxland.fi/docs/setting-edd-members/).

**Comment by planetahuevo** [comment]
I already read that info and is not clear. 
I will go with the official one then.

Thanks

**Comment by samikeijonen** [comment]
In short I'd say the biggest difference is that this plugin membership is based on time you set. And in content restriction plugin membership is based on the download you purchase. But I have never used that plugin on live site so it's hard to tell more details about it.

Note that you can try this plugin for free, that's one reason why it's here on Github.

**Comment by samikeijonen** [comment]
> I already read that info and is not clear. 

If you have more specific questions what's not clear, I can try to explain more details.

**Comment by planetahuevo** [comment]
Thank you for the answer. That is what I was looking for. :+1: 
Now is time to test and decide. 
Thanks!
