### ISSUE TITLE
Integration with Recurring Payments

### ISSUE THREAD

**Issue by pippinsplugins** [samikeijonen/edd-members#7]
I'd love to see this integrated with Recurring Payments since the plugins are pretty closely related. Interested?

**Comment by samikeijonen** [comment]
Thanks! I will look into this when I recover from new years party:)

**Comment by pippinsplugins** [comment]
Let me know if you have any questions.

**Comment by samikeijonen** [comment]
Here is first pass for supporting EDD Recurring Payments Plugin. I have couple of question.

1. Would you like to see checkbox `Active Subscribers Only?` in singular post type when EDD recurring is active?
2. Would you like to see similar checkbox in settings page (Downloads >> Settings >> Extensions) if site owner wants to make all posts private at once?

**Comment by pippinsplugins** [comment]
Looks good!

1. Yeah, that would be great. That way admins can choose whether a recurring subscription is required.

2. Yep!

**Comment by samikeijonen** [comment]
Cool, I'll add those tomorrow.

**Comment by samikeijonen** [comment]
Here is second commit for adding `Active Subscribers Only` checkbox in singular post type and in settings.

**Comment by samikeijonen** [comment]
This is pretty much done for the moment. Let me know if there is something else we can do.
