### ISSUE TITLE
Allow content for everyone

### ISSUE THREAD

**Issue by samikeijonen** [samikeijonen/edd-members#8]
There should be way to show content for all even if the content is private. This is useful for intro text. This could be done 2 ways.

1. With shortcode
2. With custom metabox

At this point I'd go for custom metabox.

**Comment by tnorthcutt** [comment]
Just out of curiosity, why would you got for a custom metabox instead of shortcodes? I'm not at all disagreeing – just eager to hear the reason :smile:

**Comment by samikeijonen** [comment]
I don't remember anymore :) Anyways there is a [shorcode](https://github.com/samikeijonen/edd-members/blob/master/includes/shortcodes.php#L39) for this. 

I'm closing this for now.

**Comment by tnorthcutt** [comment]
Doesn't that shortcode only show the content to people who are members? If that's right, perhaps a shortcode that does the opposite (e.g. `edd_members_public_content`) would be helpful?

**Comment by samikeijonen** [comment]
Yes but in shortcode `message` attribute you can show content for non members. Or if you leave `message` attribute empty, general settings will show the content for them.

Or if you write content outside of shortcode all users can see that.
