### ISSUE TITLE
Affiliate WP Support

### ISSUE THREAD

**Issue by flowdee** [samikeijonen/edd-members#9]
possible to get an integration for edd-members to https://affiliatewp.com/

**Comment by samikeijonen** [comment]
You mean the plugin that @pippinplugins and @sumobi build? What kind of integration you have in mind? I have never used it.

**Comment by flowdee** [comment]
Well with affiliatewp you earn money for user registration, is this already possible to comebin with the purchase of membership payments of your plugin? dont know :)

**Comment by samikeijonen** [comment]
Sorry I'm still not sure what you mean:)

Do you just mean that I should start affiliate program so that people could link to my site and get some share of the purchases? I have consider it but it's not top of my list.

**Comment by samikeijonen** [comment]
Closing this for now.
